language: java
jdk: openjdk8

sudo: required

service:
  - docker

after_success:
  - docker build -t mperrault/carrental .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mperrault/carrental
  - zip travis.zip Dockerrun.aws.json

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: carrental2
  env: Carrental2-env
  bucket_name: elasticbeanstalk-us-east-2-405500147375
  bucket_path: carrental2
  zip_file: travis.zip
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
